# Generated by Django 4.0.2 on 2022-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shopunit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
